// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RunnerStats.Data.Context;

#nullable disable

namespace RunnerStats.Migrations
{
    [DbContext(typeof(RunnerStatsContext))]
    partial class RunnerStatsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RunnerStats.Models.Entities.Nutrition", b =>
                {
                    b.Property<int>("NutritionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NutritionId"));

                    b.Property<string>("AdditionalNotes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("GoalMaintainWeight")
                        .HasColumnType("bit");

                    b.Property<bool>("GoalMuscleGain")
                        .HasColumnType("bit");

                    b.Property<bool>("GoalWeightLoss")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCeliac")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDiabetic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("bit");

                    b.Property<bool>("LactoseIntolerant")
                        .HasColumnType("bit");

                    b.Property<int>("RunnerId")
                        .HasColumnType("int");

                    b.HasKey("NutritionId");

                    b.HasIndex("RunnerId")
                        .IsUnique();

                    b.ToTable("Nutritions");
                });

            modelBuilder.Entity("RunnerStats.Models.Entities.Race", b =>
                {
                    b.Property<int>("IdRace")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRace"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<double>("DurationMinutes")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RunnerId")
                        .HasColumnType("int");

                    b.HasKey("IdRace");

                    b.HasIndex("RunnerId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("RunnerStats.Models.Entities.Runner", b =>
                {
                    b.Property<int>("IdRunner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRunner"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int?>("Experience")
                        .HasColumnType("int");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TotalRaces")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("IdRunner");

                    b.ToTable("Runners");
                });

            modelBuilder.Entity("RunnerStats.Models.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RunnerId")
                        .HasColumnType("int");

                    b.HasKey("IdUser");

                    b.HasIndex("RunnerId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RunnerStats.Models.Entities.Nutrition", b =>
                {
                    b.HasOne("RunnerStats.Models.Entities.Runner", "Runner")
                        .WithOne("Nutrition")
                        .HasForeignKey("RunnerStats.Models.Entities.Nutrition", "RunnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Runner");
                });

            modelBuilder.Entity("RunnerStats.Models.Entities.Race", b =>
                {
                    b.HasOne("RunnerStats.Models.Entities.Runner", "Runner")
                        .WithMany("Races")
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Runner");
                });

            modelBuilder.Entity("RunnerStats.Models.Entities.User", b =>
                {
                    b.HasOne("RunnerStats.Models.Entities.Runner", "Runner")
                        .WithOne("User")
                        .HasForeignKey("RunnerStats.Models.Entities.User", "RunnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Runner");
                });

            modelBuilder.Entity("RunnerStats.Models.Entities.Runner", b =>
                {
                    b.Navigation("Nutrition")
                        .IsRequired();

                    b.Navigation("Races");

                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
